apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Use the staging environment for testing
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: sqlbrainbox@gmail.com # Replace with your actual email
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key
      name: letsencrypt-staging-private-key
    solvers:
      - http01:
          ingress:
            # Specify the class of your Ingress controller (e.g., nginx)
            class: nginx
