# .github/ISSUE_TEMPLATE/config.yml
blank_issues_enabled: false
contact_links:
  - name: ❓ Support
    url: https://github.com/YourOrg/OnFly-Image-Optimization/discussions
    about: Ask questions or get help
