name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Skip Build if Commit Message Contains [skip ci]
        if: ${{ contains(github.event.head_commit.message, '[skip ci]') == false }}
        run: echo "Proceeding with build..."

      - name: Set Short SHA
        run: | 
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/supabase-onfly:${{ env.SHORT_SHA }}

      - name: config Git Author
        run: | 
          git config --local user.email "gambhir786191ss@gmail.com"
          git config --local user.name "gambhirsharma"
      
      - name: Update Helm Chart with new image tag
        run: | 
          sed -i "s/tag:.*/tag: ${{ env.SHORT_SHA }}/" ./charts/front-end/values.yaml
          git add ./charts/front-end/values.yaml
          git commit -m "Updated image tag to ${{ env.SHORT_SHA }}"
          git push 
